# Generated by Django 3.2.7 on 2021-10-01 10:46

import base.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.CharField(help_text='Чтобы никаких шмактеров!', max_length=255, validators=[base.models.validate_actor], verbose_name='Актер в главной роли'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(help_text='Между 1900 и 2021', validators=[django.core.validators.MinValueValidator(1900, message='Год должен быть 1900 или больше'), django.core.validators.MaxValueValidator(2021, message='Год должен быть 2021 или меньше')], verbose_name='Год Релиза'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Не пишите одно слово тест', max_length=50, validators=[base.models.validate_title], verbose_name='Название Фильма'),
        ),
    ]
